<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <AssemblyName>F8SkeletonStreamer</AssemblyName>
    <RootNamespace>F8SkeletonStreamer</RootNamespace>
    <OutputPath>..\bin\F8SkeletonStreamer\BepInEx\plugins\F8SkeletonStreamer\</OutputPath>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.11" ExcludeAssets="runtime" />
    <PackageReference Include="HarmonyX" Version="2.4.2" ExcludeAssets="runtime" />
    <PackageReference Include="LitJson" Version="0.19.0" PrivateAssets="all" />
    <PackageReference Include="UnityEngine.Core" Version="5.6.0" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>
</Project>
